name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: docfx.json
        
    - name: List Folders
      run: |
        cd ./R6Stat-Sharp
        ls
        
    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: ./R6Stat-Sharp/_site
        GH_PAT: ${{ secrets.GH_PAT }}
